<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Default Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default filesystem disk that should be used
    | by the framework. The "local" disk, as well as a variety of cloud
    | based disks are available to your application.
    |
    */
    'default' => env('FILESYSTEM_DISK', 'local'),

    /*
    |--------------------------------------------------------------------------
    | Filesystem Disks
    |--------------------------------------------------------------------------
    |
    | Here you may configure as many filesystem "disks" as you wish, and you
    | may even configure multiple disks of the same driver.
    |
    | Supported Drivers: "local", "s3"
    |
    */
    'disks' => [
        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
            'url' => env('APP_URL') . '/storage',
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL') . '/storage/public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'prefix' => env('AWS_PREFIX', ''),
        ],

        'gcs' => [
            'driver' => 'gcs',
            'key' => env('GCS_ACCESS_KEY_ID'), // HMAC Key
            'secret' => env('GCS_SECRET_ACCESS_KEY'), // HMAC Secret
            'bucket' => env('GCS_BUCKET'),
        ],

        'azure' => [
            'driver' => 'azure',
            'name' => env('AZURE_STORAGE_NAME'),
            'key' => env('AZURE_STORAGE_KEY'),
            'container' => env('AZURE_STORAGE_CONTAINER'),
        ],

        'temp' => [
            'driver' => 'memory',
        ],

        'ftp' => [
            'driver' => 'ftp',
            'host' => env('FTP_HOST'),
            'username' => env('FTP_USERNAME'),
            'password' => env('FTP_PASSWORD'),
            'port' => env('FTP_PORT', 21),
            'root' => env('FTP_ROOT', ''),
            'ssl' => env('FTP_SSL', false),
            'passive' => true,
        ],

        'sftp' => [
            'driver' => 'sftp',
            'host' => env('SFTP_HOST'),
            'username' => env('SFTP_USERNAME'),
            'password' => env('SFTP_PASSWORD'),
            'privateKey' => env('SFTP_PRIVATE_KEY'),
            'passphrase' => env('SFTP_PASSPHRASE'),
            'port' => env('SFTP_PORT', 22),
            'root' => env('SFTP_ROOT', ''),
        ],

        'archive' => [
            'driver' => 'zip',
            'path' => storage_path('app/archive.zip'),
        ],

        'webdav' => [
            'driver' => 'webdav',
            'baseUri' => env('WEBDAV_BASE_URI'),
            'username' => env('WEBDAV_USERNAME'),
            'password' => env('WEBDAV_PASSWORD'),
            'authType' => env('WEBDAV_AUTH_TYPE', 'basic'),
        ],

        'null' => [
            'driver' => 'null',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Temporary URL Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may configure the behavior of temporary URLs generated by
    | the storage system, such as the threshold for duration vs timestamp.
    |
    */
    'links' => [
        'threshold' => 1000000000, // Timestamps before this are treated as durations (seconds)
        'signed_route' => '/storage/signed/view',
    ],
];
